# Generated by Django 4.2.3 on 2023-07-09 18:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("name",),
                "verbose_name": "Category",
                "verbose_name_plural": "categories",
            },
        ),
    ]
