# Generated by Django 4.2.3 on 2023-07-10 21:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={
                "ordering": ["-modified_at"],
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
            },
        ),
    ]
