# Generated by Django 4.2.3 on 2023-07-11 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0002_alter_conversation_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversationmessage",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="conversations.conversation",
            ),
        ),
    ]
