# Generated by Django 4.2.3 on 2023-07-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0003_alter_conversationmessage_conversation"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationmessage",
            name="pending_to_read",
            field=models.BooleanField(default=True),
        ),
    ]
