# Generated by Django 4.2.3 on 2023-07-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0004_conversationmessage_pending_to_read"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversationmessage",
            name="pending_to_read",
        ),
        migrations.AddField(
            model_name="conversationmessage",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
